### ISSUE TITLE
`bin` folder location

### ISSUE THREAD

**Issue by Hongbo-Miao** [mikejoh/cloud-provider-cloudlycke#1]
Thanks @mikejoh for the awesome [blog](https://medium.com/@m.json/the-kubernetes-cloud-controller-manager-d440af0d2be5)!

I have a question, for this line in the Dockefile, it tries to copy `bin/cloudlycke-cloud-controller-manager`, however, there is no `bin` folder in this repo.

https://github.com/mikejoh/cloud-provider-cloudlycke/blob/e5dd15403b9a7724ae2de54e1959ae89da4367f9/Dockerfile#L4

Would you mind clarifying this part? Thanks! 😃

**Comment by mikejoh** [comment]
Thanks! :pray: 

Through the `Makefile` and if you run `make build-linux` the compiled binary will end up in `bin/`. With that said i know that this repository is a bit outdated, if you're testing your way through it and end up stuck you can reach out to me on the official Kubernetes Slack (**mikejoh**).

**Comment by Hongbo-Miao** [comment]
Thank you so much, @mikejoh ! 😊
